
#configs
title: mayankkhera.com
email:
twitter_username: username
github_username: username


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dirt
search: false

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _posts
  - _resources
  - _books

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mayank Khera"
  avatar : "/assets/images/mayank-profile.jpg"
  bio    : "I am a product builder who enjoys writing about technology, career growth and startups"
  location: "London, UK"
  linkedin: mayankkhera
  

defaults:
  
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
      
      
  
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      

  # resources
  - scope:
      path: ""
      type: resources
    values:
      layout: single
      related: false
      author_profile: false
      toc: true
      toc_label: "Contents"
      

  # books
  - scope:
      path: ""
      type: books
    values:
      layout: single
      related: false
      author_profile: false
      

        
# collections
collections:
  resources:
    output: true
  books:
    output: true
    permalink: /books/:title/

    

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/